apiVersion: v1
kind: Namespace
metadata:
  name: zeet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeet-admin
  namespace: zeet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeet-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: zeet-admin
  namespace: zeet
---
apiVersion: v1
kind: Secret
metadata:
  name: zeet-admin-token
  namespace: zeet
  annotations:
    kubernetes.io/service-account.name: zeet-admin
type: kubernetes.io/service-account-token